### ISSUE TITLE
Tema legal

### ISSUE THREAD

**Issue by yzk23** [walberfa/projetoTCC1#1]
Gostei do teu projeto de TCC, amigo. Tu fez esse documento no Word ou no LaTeX?

**Comment by walberfa** [comment]
> Gostei do teu projeto de TCC, amigo. Tu fez esse documento no Word ou no LaTeX?

Amigo, foi no word mesmo kk Ainda preciso aprender o LaTeX

**Comment by yzk23** [comment]
É bem fácil. É só questão de familiaridade mesmo. Quiser ajuda tô aqui.
